Repository GSharker/G-Shark, pull requests merged in 2021-07, with the labels that each got.

#167 Regular polygon and Rectangle
  src/GShark.Test.XUnit/DebugFiles/GHDebug.gh
  src/GShark.Test.XUnit/Geometry/PolygonTests.cs
  src/GShark/Geometry/Polygon.cs
Labels: enhancement, geometry

#178 PointAt clarified the return
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Operation/Evaluation.cs
Labels: Refactor

#186 Renamed ControlPoints and HomogenizedPoints.
  src/GShark.Test.XUnit/Geometry/ArcTests.cs
  src/GShark.Test.XUnit/Geometry/CircleTests.cs
  src/GShark.Test.XUnit/Geometry/LineTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
  src/GShark.Test.XUnit/Operation/FittingTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark.Test.XUnit/Operation/TessellationTests.cs
  src/GShark/Core/BoundingBoxTree/BoundingBoxOperations.cs
  src/GShark/Core/BoundingBoxTree/LazyCurveBBT.cs
  src/GShark/Geometry/Arc.cs
  src/GShark/Geometry/Circle.cs
  src/GShark/Geometry/Interfaces/ICurve.cs
  src/GShark/Geometry/Line.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Geometry/Polyline.cs
  src/GShark/Operation/Analyze.cs
  src/GShark/Operation/Divide.cs
  src/GShark/Operation/Evaluation.cs
  src/GShark/Operation/Modify.cs
  src/GShark/Operation/Tessellation.cs
Labels: Refactor

#185 Dev/mibi/refactor vector3 list indexes
  src/GShark.Test.XUnit/Geometry/ArcTests.cs
  src/GShark.Test.XUnit/Geometry/CircleTests.cs
  src/GShark.Test.XUnit/Geometry/LineTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
  src/GShark.Test.XUnit/Geometry/Point3Tests.cs
  src/GShark.Test.XUnit/Geometry/Point4Tests.cs
  src/GShark.Test.XUnit/Geometry/Vector3Tests.cs
  src/GShark.Test.XUnit/Geometry/VectorTests.cs
  src/GShark.Test.XUnit/Operation/FittingTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark.Test.XUnit/Operation/OffsetTests.cs
  src/GShark.Test.XUnit/Operation/TessellationTests.cs
  src/GShark/Core/BoundingBoxTree/BoundingBoxOperations.cs
  src/GShark/Core/BoundingBoxTree/LazyCurveBBT.cs
  src/GShark/Core/KnotVector.cs
  src/GShark/ExtendedMethods/ExtendedEnumerable.cs
  src/GShark/Geometry/Arc.cs
  src/GShark/Geometry/Circle.cs
  src/GShark/Geometry/Interfaces/ICurve.cs
  src/GShark/Geometry/Line.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Geometry/Polyline.cs
  src/GShark/Geometry/Vector.cs
  src/GShark/Operation/Analyze.cs
  src/GShark/Operation/Divide.cs
  src/GShark/Operation/Evaluation.cs
  src/GShark/Operation/Fitting.cs
  src/GShark/Operation/Modify.cs
  src/GShark/Operation/Tessellation.cs
Labels: Refactor, enhancement

#187 Dev/mibi/refactor vector3 angle radians
  src/GShark.Test.XUnit/Geometry/VectorTests.cs
  src/GShark/Core/LinearAlgebra.cs
  src/GShark/Core/Transform.cs
  src/GShark/Geometry/Arc.cs
  src/GShark/Geometry/Plane.cs
  src/GShark/Geometry/Vector.cs
  src/GShark/Geometry/Vector3.cs
Labels: Refactor

#193 Removed old toDos.
  src/GShark.Test.XUnit/Operation/IntersectionTests.cs
  src/GShark/Core/GeoSharkMath.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/Point3.cs
  src/GShark/Geometry/Point4.cs
  src/GShark/Geometry/Vector.cs
  src/GShark/Geometry/Vector3.cs
  src/GShark/Operation/IntersectionRefiner.cs
Labels: Refactor, enhancement

#195 Refactor Plane. Add validity check.
  src/GShark.Test.XUnit/Core/TrigonometryTests.cs
  src/GShark.Test.XUnit/Geometry/PlaneTests.cs
  src/GShark.Test.XUnit/Operation/FittingTests.cs
  src/GShark/Core/Trigonometry.cs
  src/GShark/Geometry/Plane.cs
  src/GShark/Operation/Tessellation.cs
Labels: Refactor, geometry

#196 Dev/mibi/review surface class
  src/GShark.Test.XUnit/Data/NurbsCurveCollection.cs
  src/GShark.Test.XUnit/Data/NurbsSurfaceCollection.cs
  src/GShark.Test.XUnit/DebugFiles/GHDebug.gh
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark.Test.XUnit/Operation/EvaluationTests.cs
  src/GShark.Test.XUnit/VerbTests.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Operation/Evaluation.cs
Labels: Refactor

#208 Convex hull 3d initial commit.
  src/GShark.Test.XUnit/DebugFiles/GHDebug.gh
  src/GShark.Test.XUnit/DebugFiles/GHDebug_Curves.gh
  src/GShark.Test.XUnit/Geometry/ConvexHullTests.cs
  src/GShark/Geometry/ConvexHull.cs
Labels: enhancement

#214 Dev/guma/divide curve methods
  src/GShark.Test.XUnit/Operation/DivideTests.cs
  src/GShark/ExtendedMethods/Curve.cs
  src/GShark/Operation/Analyze.cs
  src/GShark/Operation/Divide.cs
  src/GShark/Operation/Modify.cs
Labels: Refactor, enhancement

#210 Dev/mibi/surface normal at
  src/GShark.Test.XUnit/Data/NurbsSurfaceCollection.cs
  src/GShark.Test.XUnit/DebugFiles/GHDebugSurface.gh
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark.Test.XUnit/Operation/EvaluationTests.cs
  src/GShark.Test.XUnit/VerbTests.cs
  src/GShark/Geometry/Enum/SurfaceDirection.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Geometry/Point3.cs
  src/GShark/Geometry/Point4.cs
  src/GShark/Geometry/Vector.cs
  src/GShark/Operation/Evaluation.cs
Labels: Refactor, enhancement

#220 Update README.md
  README.md
Labels: enhancement, minor, refactor
