Repository GSharker/G-Shark, pull requests merged in 2021-08, with the labels that each got.

#230 Dev/mibi/curve constructors
  src/GShark.Test.XUnit/Core/SetsTests.cs
  src/GShark.Test.XUnit/Data/NurbsCurveCollection.cs
  src/GShark.Test.XUnit/DebugFiles/GHDebug_Curves.gh
  src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
  src/GShark.Test.XUnit/Operation/AnalyzeTests.cs
  src/GShark.Test.XUnit/Operation/DivideTests.cs
  src/GShark.Test.XUnit/Operation/EvaluationTests.cs
  src/GShark.Test.XUnit/Operation/IntersectionTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark.Test.XUnit/Operation/TessellationTests.cs
  src/GShark/Core/KnotVector.cs
  src/GShark/ExtendedMethods/Curve.cs
  src/GShark/Geometry/Arc.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/Point3.cs
  src/GShark/Geometry/Point4.cs
  src/GShark/Operation/Analyze.cs
  src/GShark/Operation/Divide.cs
  src/GShark/Operation/Evaluation.cs
  src/GShark/Operation/Fitting.cs
  src/GShark/Operation/Modify.cs
Labels: refactor

#237 Dev/mibi/surface closest parameter
  src/GShark.Test.XUnit/DebugFiles/GHDebugSurface.gh
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark.Test.XUnit/Operation/AnalyzeTests.cs
  src/GShark.Test.XUnit/VerbTests.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Geometry/Vector3.cs
  src/GShark/Operation/Analyze.cs
  src/GShark/Operation/Evaluation.cs
Labels: enhancement

#244 Dev/mibi/elevate curve degree
  src/GShark.Test.XUnit/DebugFiles/GHDebugSurface.gh
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark.Test.XUnit/VerbTests.cs
  src/GShark/Geometry/Point3.cs
  src/GShark/Geometry/Point4.cs
  src/GShark/Operation/Modify.cs
Labels: enhancement

#246 Dev/mibi/join curve
  src/GShark.Test.XUnit/DebugFiles/GHDebug_Curves.gh
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark/Core/LinearAlgebra.cs
  src/GShark/Geometry/Arc.cs
  src/GShark/Operation/Modify.cs
Labels: bug, enhancement

#224 LoftedSurface finished
  media/diagram.svg
  src/GShark.Test.XUnit/Data/NurbsCurveCollection.cs
  src/GShark.Test.XUnit/DebugFiles/DynamoDebug.dyn
  src/GShark.Test.XUnit/DebugFiles/GHDebugSurface.gh
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark/Core/Sets.cs
  src/GShark/Geometry/Enum/LoftType.cs
  src/GShark/Geometry/NurbsSurface.cs
Labels: enhancement

#250 Fixed problem for isClosed.
  src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/NurbsSurface.cs
Labels: bug

#267 Dev/mibi/rename location points
  src/GShark.Test.XUnit/Geometry/ArcTests.cs
  src/GShark.Test.XUnit/Geometry/CircleTests.cs
  src/GShark.Test.XUnit/Geometry/LineTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
  src/GShark.Test.XUnit/Operation/AnalyzeTests.cs
  src/GShark.Test.XUnit/Operation/DivideTests.cs
  src/GShark.Test.XUnit/Operation/FittingTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark.Test.XUnit/Operation/TessellationTests.cs
  src/GShark/Core/BoundingBoxTree/BoundingBoxOperations.cs
  src/GShark/Core/BoundingBoxTree/LazyCurveBBT.cs
  src/GShark/ExtendedMethods/Curve.cs
  src/GShark/Geometry/Arc.cs
  src/GShark/Geometry/Circle.cs
  src/GShark/Geometry/Interfaces/ICurve.cs
  src/GShark/Geometry/Line.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Geometry/Polyline.cs
  src/GShark/Operation/Analyze.cs
  src/GShark/Operation/Evaluation.cs
  src/GShark/Operation/Tessellation.cs
Labels: refactor

#271 Implement icurve methods and properties.
  src/GShark.Test.XUnit/Geometry/LineTests.cs
  src/GShark.Test.XUnit/Operation/IntersectionTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark.Test.XUnit/Operation/OffsetTests.cs
  src/GShark.Test.XUnit/Operation/TessellationTests.cs
  src/GShark/Core/Transform.cs
  src/GShark/Geometry/Line.cs
  src/GShark/Operation/Intersect.cs
  src/GShark/Operation/Offset.cs
Labels: enhancement, refactor

#272 Dev/mibi/arc inheritance circle
  src/GShark.Test.XUnit/DebugFiles/GHDebug_Curves.gh
  src/GShark.Test.XUnit/Geometry/ArcTests.cs
  src/GShark.Test.XUnit/Geometry/CircleTests.cs
  src/GShark/Geometry/Arc.cs
  src/GShark/Geometry/Circle.cs
Labels: enhancement, refactor

#276 Dev/mibi/implements ICurve to circle
  src/GShark.Test.XUnit/DebugFiles/GHDebug_Curves.gh
  src/GShark.Test.XUnit/Geometry/ArcTests.cs
  src/GShark.Test.XUnit/Geometry/CircleTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark/Geometry/Arc.cs
  src/GShark/Geometry/Circle.cs
  src/GShark/Geometry/Line.cs
Labels: enhancement, refactor

#277 Dev/mibi/surfaces tests and refactoring
  src/GShark.Test.XUnit/Data/NurbsCurveCollection.cs
  src/GShark.Test.XUnit/DebugFiles/GHDebugSurface.gh
  src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark.Test.XUnit/Geometry/PolylineTests.cs
  src/GShark.Test.XUnit/Operation/FittingTests.cs
  src/GShark.Test.XUnit/Operation/OffsetTests.cs
  src/GShark.Test.XUnit/Operation/TessellationTests.cs
  src/GShark/Geometry/Arc.cs
  src/GShark/Geometry/NurbsSurface.cs
Labels: refactor

#279 Dev/guma/polyline implements icurve
  src/GShark.Test.XUnit/DebugFiles/GHDebug_Curves.gh
  src/GShark.Test.XUnit/Geometry/PolygonTests.cs
  src/GShark.Test.XUnit/Geometry/PolylineTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark.Test.XUnit/Operation/OffsetTests.cs
  src/GShark.Test.XUnit/Operation/TessellationTests.cs
  src/GShark/Geometry/Line.cs
  src/GShark/Geometry/Polygon.cs
  src/GShark/Geometry/Polyline.cs
  src/GShark/Operation/Intersect.cs
  src/GShark/Operation/Offset.cs
Labels: enhancement, refactor

#284 Dev/mibi/ruled surface
  src/GShark.Test.XUnit/DebugFiles/GHDebugSurface.gh
  src/GShark.Test.XUnit/Geometry/ArcTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark.Test.XUnit/Geometry/PolygonTests.cs
  src/GShark.Test.XUnit/Geometry/PolylineTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark.Test.XUnit/Operation/OffsetTests.cs
  src/GShark/ExtendedMethods/Curve.cs
  src/GShark/Geometry/Arc.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Geometry/Vector3.cs
  src/GShark/Operation/Intersect.cs
  src/GShark/Operation/Modify.cs
  src/GShark/Operation/Offset.cs
Labels: enhancement, refactor

#298 Dev/mibi/nurbs curve implements icurve
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Operation/Analyze.cs
  src/GShark/Operation/Divide.cs
  src/GShark/Operation/Offset.cs
Labels: enhancement, refactor

#301 Dev/mibi/refactor loft surface
  src/GShark.Test.XUnit/DebugFiles/GHDebugSurface.gh
  src/GShark/Geometry/NurbsSurface.cs
Labels: enhancement, refactor
