Repository GSharker/G-Shark, pull requests merged in 2021-09, with the labels that each got.

#306 Fix docs and build workflows.
  .github/workflows/build-docs.yml
  .github/workflows/generate_diagram.yml
  .github/workflows/publish-on-release.yml
  media/diagram.svg
Labels: patch

#316 Rename method. Move method.
  src/GShark.Test.XUnit/Core/TrigonometryTests.cs
  src/GShark/Core/Trigonometry.cs
  src/GShark/Geometry/Circle.cs
  src/GShark/Operation/Analyze.cs
Labels: refactor

#317 Remove LinearAlgebra class. Move methods to appropriate namespaces.
  src/GShark.Test.XUnit/Core/LinearAlgebraTests.cs
  src/GShark.Test.XUnit/Core/MathTests.cs
  src/GShark.Test.XUnit/Core/TransformTests.cs
  src/GShark/Core/GSharkMath.cs
  src/GShark/Core/LinearAlgebra.cs
  src/GShark/Core/Transform.cs
  src/GShark/Core/Trigonometry.cs
  src/GShark/Operation/Evaluation.cs
  src/GShark/Operation/Modify.cs
Labels: refactor

#320 Move all interfaces and enums to GShark.Interfaces, GShark.Enumerations.
  src/GShark.Test.XUnit/Geometry/LineTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark.Test.XUnit/Geometry/PolygonTests.cs
  src/GShark.Test.XUnit/Geometry/PolylineTests.cs
  src/GShark.Test.XUnit/Operation/AnalyzeTests.cs
  src/GShark.Test.XUnit/Operation/DivideTests.cs
  src/GShark.Test.XUnit/Operation/IntersectionTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark.Test.XUnit/Operation/OffsetTests.cs
  src/GShark/Core/BoundingBoxTree/LazyCurveBBT.cs
  src/GShark/Enumerations/EvaluateSurfaceDirection.cs
  src/GShark/Enumerations/LoftType.cs
  src/GShark/Enumerations/SplitDirection.cs
  src/GShark/Enumerations/SurfaceDirection.cs
  src/GShark/ExtendedMethods/Curve.cs
  src/GShark/ExtendedMethods/Surface.cs
  src/GShark/Geometry/Arc.cs
  src/GShark/Geometry/Circle.cs
  src/GShark/Geometry/Line.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Geometry/Plane.cs
  src/GShark/Geometry/Polyline.cs
  src/GShark/Interfaces/ICurve.cs
  src/GShark/Interfaces/ISerializable.cs
  src/GShark/Interfaces/ITransformable.cs
  src/GShark/Operation/Analyze.cs
  src/GShark/Operation/Divide.cs
  src/GShark/Operation/Evaluation.cs
  src/GShark/Operation/Intersect.cs
  src/GShark/Operation/IntersectionRefiner.cs
  src/GShark/Operation/Modify.cs
  src/GShark/Operation/Tessellation.cs
  src/GShark/Optimization/CurvePlaneIntersectionObjectives.cs
  src/GShark/Optimization/CurvesIntersectionObjectives.cs
Labels: refactor

#321 Refactor Line and Circle.
  src/GShark.Test.XUnit/DebugFiles/GHDebug_Curves.gh
  src/GShark.Test.XUnit/Geometry/CircleTests.cs
  src/GShark.Test.XUnit/Geometry/LineTests.cs
  src/GShark/Geometry/Arc.cs
  src/GShark/Geometry/Circle.cs
  src/GShark/Geometry/Line.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/Polyline.cs
  src/GShark/Interfaces/ICurve.cs
Labels: refactor

#323 Refactor ``NurbsCurve``
  src/GShark.Test.XUnit/DebugFiles/GHDebug_Curves.gh
  src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
  src/GShark.Test.XUnit/Geometry/PolygonTests.cs
  src/GShark.Test.XUnit/Geometry/PolylineTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark/Core/KnotVector.cs
  src/GShark/ExtendedMethods/Curve.cs
  src/GShark/Geometry/Circle.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/Polyline.cs
  src/GShark/Interfaces/ICurve.cs
  src/GShark/Operation/Modify.cs
Labels: refactor

#325 Refactors Intersection namespaces. Adds placeholder folders.
  src/GShark.Test.XUnit/Operation/IntersectionTests.cs
  src/GShark/GShark.csproj
  src/GShark/Geometry/Circle.cs
  src/GShark/Geometry/Polyline.cs
  src/GShark/Interfaces/IBoundingBoxTree.cs
  src/GShark/Intersection/BoundingBoxTree/BoundingBoxOperations.cs
  src/GShark/Intersection/BoundingBoxTree/LazyCurveBBT.cs
  src/GShark/Intersection/CurvePlaneIntersectionResult.cs
  src/GShark/Intersection/CurvesIntersectionResult.cs
  src/GShark/Intersection/Intersect.cs
  src/GShark/Intersection/IntersectionRefiner.cs
Labels: refactor

#326 Update EpsilonEquals
  src/GShark/Geometry/Point3.cs
Labels: bug

#328 Normalise sub-curve domain.
  src/GShark.Test.XUnit/Operation/DivideTests.cs
  src/GShark/ExtendedMethods/Curve.cs
Labels: bug

#327 Change knot domain.
  src/GShark.Test.XUnit/Geometry/CircleTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark/Core/KnotVector.cs
  src/GShark/ExtendedMethods/Curve.cs
  src/GShark/Geometry/Circle.cs
  src/GShark/Geometry/Line.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Geometry/Polyline.cs
  src/GShark/Intersection/BoundingBoxTree/LazyCurveBBT.cs
Labels: refactor

#333 Refactor join method.
  src/GShark/GShark.csproj
  src/GShark/Geometry/Polyline.cs
  src/GShark/Operation/Modify.cs
Labels: refactor

#338 Removed ``Curve`` and ``Surface`` into ``ExtendedMethods``.
  src/GShark/Core/CurveHelpers.cs
  src/GShark/ExtendedMethods/Curve.cs
  src/GShark/ExtendedMethods/Surface.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/NurbsSurface.cs
Labels: refactor

#336 Joincurve and extrema
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark/Core/CurveHelpers.cs
  src/GShark/Core/Trigonometry.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Operation/Evaluation.cs
  src/GShark/Operation/Modify.cs
  src/GShark/Operation/Utilities/Extrema.cs
Labels: enhancement, refactor

#345 Extracted ``Fitting``
  src/GShark.Test.XUnit/Fitting/CurveTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
  src/GShark/Core/CurveHelpers.cs
  src/GShark/Fitting/Curve.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/NurbsSurface.cs
Labels: refactor

#346 Introduced abstract ``NurbsBase``
  src/GShark.Test.XUnit/Data/NurbsCurveCollection.cs
  src/GShark.Test.XUnit/DebugFiles/DynamoDebug.dyn
  src/GShark.Test.XUnit/Fitting/CurveTests.cs
  src/GShark.Test.XUnit/Geometry/ArcTests.cs
  src/GShark.Test.XUnit/Geometry/CircleTests.cs
  src/GShark.Test.XUnit/Geometry/LineTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark.Test.XUnit/Geometry/PolygonTests.cs
  src/GShark.Test.XUnit/Geometry/PolylineTests.cs
  src/GShark.Test.XUnit/Operation/AnalyzeTests.cs
  src/GShark.Test.XUnit/Operation/EvaluationTests.cs
  src/GShark.Test.XUnit/Operation/IntersectionTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark.Test.XUnit/Sampling/CurveTests.cs
  src/GShark.Test.XUnit/VerbTests.cs
  src/GShark/Core/CollectionHelpers.cs
  src/GShark/Core/CurveHelpers.cs
  src/GShark/Fitting/Curve.cs
  src/GShark/Geometry/BoundingBox.cs
  src/GShark/Geometry/Circle.cs
  src/GShark/Geometry/ConvexHull.cs
  src/GShark/Geometry/Line.cs
  src/GShark/Geometry/NurbsBase.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Geometry/Polyline.cs
  src/GShark/Interfaces/IBoundingBoxTree.cs
  src/GShark/Intersection/BoundingBoxTree/BoundingBoxOperations.cs
  src/GShark/Intersection/BoundingBoxTree/LazyCurveBBT.cs
  src/GShark/Intersection/CurvePlaneIntersectionResult.cs
  src/GShark/Intersection/CurvesIntersectionResult.cs
  src/GShark/Intersection/Intersect.cs
  src/GShark/Intersection/IntersectionRefiner.cs
  src/GShark/Operation/Analyze.cs
  src/GShark/Operation/Evaluation.cs
  src/GShark/Operation/Modify.cs
  src/GShark/Optimization/CurvePlaneIntersectionObjectives.cs
  src/GShark/Optimization/CurvesIntersectionObjectives.cs
  src/GShark/Optimization/IObjectiveFunction.cs
  src/GShark/Optimization/MinimizationResult.cs
  src/GShark/Optimization/Minimizer.cs
  src/GShark/Sampling/Curve.cs
  src/GShark/Sampling/Surface.cs
Labels: enhancement, refactor

#347 Added PolyCurve
  src/GShark.Test.XUnit/DebugFiles/GHDebug_Curves.gh
  src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark.Test.XUnit/Geometry/PolyCurveTests.cs
  src/GShark.Test.XUnit/Geometry/PolygonTests.cs
  src/GShark.Test.XUnit/Geometry/PolylineTests.cs
  src/GShark.Test.XUnit/Operation/IntersectionTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark.Test.XUnit/Sampling/CurveTests.cs
  src/GShark/Geometry/NurbsBase.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/PolyCurve.cs
  src/GShark/Geometry/Polygon.cs
  src/GShark/Geometry/Polyline.cs
  src/GShark/Intersection/Intersect.cs
  src/GShark/Operation/Analyze.cs
  src/GShark/Operation/Evaluation.cs
  src/GShark/Optimization/CurvePlaneIntersectionObjectives.cs
Labels: enhancement

#352 Join returning a PolyCurve.
  src/GShark.Test.XUnit/DebugFiles/GHDebug_Curves.gh
  src/GShark.Test.XUnit/Geometry/PolyCurveTests.cs
  src/GShark/GShark.csproj
  src/GShark/Geometry/PolyCurve.cs
  src/GShark/Operation/Analyze.cs
  src/GShark/Operation/Modify.cs
Labels: refactor

#356 Creation of the namespace ``Modify``
  src/GShark.Test.XUnit/Data/NurbsCurveCollection.cs
  src/GShark.Test.XUnit/Data/NurbsSurfaceCollection.cs
  src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark.Test.XUnit/Modify/CurveTests.cs
  src/GShark.Test.XUnit/Modify/SurfaceTests.cs
  src/GShark.Test.XUnit/Operation/AnalyzeTests.cs
  src/GShark.Test.XUnit/Operation/EvaluationTests.cs
  src/GShark.Test.XUnit/Operation/ModifyTests.cs
  src/GShark.Test.XUnit/Sampling/CurveTests.cs
  src/GShark.Test.XUnit/Sampling/SurfaceTest.cs
  src/GShark/Core/CurveHelpers.cs
  src/GShark/Core/KnotVector.cs
  src/GShark/Geometry/NurbsBase.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Geometry/PolyCurve.cs
  src/GShark/Modify/Curve.cs
  src/GShark/Modify/Surface.cs
  src/GShark/Operation/Analyze.cs
  src/GShark/Sampling/Curve.cs
  src/GShark/Sampling/Surface.cs
  src/Operation/Sampling/Curve.cs
  src/Operation/Sampling/Surface.cs
Labels: refactor

#357 Created namespace Analyze
  src/GShark.Test.XUnit/Analyze/CurveTests.cs
  src/GShark.Test.XUnit/Analyze/SurfaceTests.cs
  src/GShark.Test.XUnit/Core/TrigonometryTests.cs
  src/GShark.Test.XUnit/Intersection/IntersectionTests.cs
  src/GShark.Test.XUnit/Operation/AnalyzeTests.cs
  src/GShark.Test.XUnit/Operation/CheckTests.cs
  src/GShark/Analyze/Curve.cs
  src/GShark/Analyze/Surface.cs
  src/GShark/Core/LegendreGaussData.cs
  src/GShark/Core/Trigonometry.cs
  src/GShark/Geometry/NurbsBase.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Operation/Analyze.cs
  src/GShark/Sampling/Curve.cs
Labels: refactor

#358 Created ``Evaluate`` namespace.
  src/GShark.Test.XUnit/Evaluate/CurveTests.cs
  src/GShark.Test.XUnit/Evaluate/SurfaceTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark/Analyze/Curve.cs
  src/GShark/Analyze/Surface.cs
  src/GShark/Core/Extrema.cs
  src/GShark/Evaluate/Curve.cs
  src/GShark/Evaluate/Surface.cs
  src/GShark/Fitting/Curve.cs
  src/GShark/Geometry/NurbsBase.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Geometry/Plane.cs
  src/GShark/Geometry/Polygon.cs
  src/GShark/Modify/Curve.cs
  src/GShark/Optimization/CurvePlaneIntersectionObjectives.cs
  src/GShark/Optimization/CurvesIntersectionObjectives.cs
  src/GShark/Sampling/Curve.cs
Labels: refactor

#359 Line inheritance NurbsBase.
  src/GShark.Test.XUnit/Data/NurbsSurfaceCollection.cs
  src/GShark.Test.XUnit/Geometry/LineTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
  src/GShark.Test.XUnit/Sampling/CurveTests.cs
  src/GShark/Geometry/Line.cs
  src/GShark/Geometry/NurbsBase.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/PolyCurve.cs
  src/GShark/Intersection/Intersect.cs
Labels: refactor

#360 ``Circle`` inheritance ``NurbsBase``
  src/GShark.Test.XUnit/Geometry/ArcTests.cs
  src/GShark.Test.XUnit/Geometry/CircleTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
  src/GShark/Geometry/Arc.cs
  src/GShark/Geometry/Circle.cs
  src/GShark/Geometry/NurbsBase.cs
  src/GShark/Geometry/PolyCurve.cs
  src/GShark/Interfaces/ICurve.cs
Labels: refactor

#361 infinite curvature bug fix
  src/GShark/Analyze/Curve.cs
Labels: bug

#370 Dev/guma/point at chord length
  src/GShark.Test.XUnit/Analyze/CurveTests.cs
  src/GShark.Test.XUnit/Data/NurbsCurveCollection.cs
  src/GShark.Test.XUnit/DebugFiles/GHDebug_Curves.gh
  src/GShark.Test.XUnit/Evaluate/CurveTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark.Test.XUnit/Sampling/CurveTests.cs
  src/GShark/Geometry/NurbsBase.cs
  src/GShark/Optimization/ChordLengthObjective.cs
Labels: enhancement, refactor

#365 converted point3 from struct to class
  src/GShark/Geometry/Point3.cs
Labels: refactor

#368 Revolved Surface
  GeometrySharkIcons.ai
  src/GShark.Test.XUnit/Data/NurbsSurfaceCollection.cs
  src/GShark.Test.XUnit/DebugFiles/GHDebugSurface.gh
  src/GShark.Test.XUnit/DebugFiles/GHDebug_Surface.gh
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark.Test.XUnit/VerbTests.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Geometry/Point3.cs
  src/GShark/Geometry/Point4.cs
Labels: enhancement
