Repository GSharker/G-Shark, pull requests merged in 2023-01, with the labels that each got.

#389 ICurve implemented
  src/GShark.Test.XUnit/Geometry/TransformTests.cs
  src/GShark/Geometry/Arc.cs
  src/GShark/Geometry/Circle.cs
  src/GShark/Geometry/Line.cs
  src/GShark/Geometry/NurbsBase.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Geometry/Plane.cs
  src/GShark/Geometry/Polyline.cs
  src/GShark/Interfaces/IGeometry.cs
Labels: minor

#393 Develop
  .github/workflows/build-and-test-on-pr.yml
  .github/workflows/build-docs.yml
  .github/workflows/create-release.yml
  .github/workflows/generate_diagram.yml
  .github/workflows/publish-on-release.yml
  .github/workflows/release-drafter.yml
  CONTRIBUTING.md
  README.md
  media/diagram.svg
  src/GShark.Test.XUnit/Core/TransformMatrixTests.cs
  src/GShark.Test.XUnit/Core/TransformTests.cs
  src/GShark.Test.XUnit/DebugFiles/GHDebug_Surface.gh
  src/GShark.Test.XUnit/GShark.Test.XUnit.csproj
  src/GShark.Test.XUnit/Geometry/ArcTests.cs
  src/GShark.Test.XUnit/Geometry/LineTests.cs
  src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
  src/GShark.Test.XUnit/Geometry/PlaneTests.cs
  src/GShark.Test.XUnit/Geometry/Point3Tests.cs
  src/GShark.Test.XUnit/Geometry/PolylineTests.cs
  src/GShark.Test.XUnit/Geometry/TransformTests.cs
  src/GShark.Test.XUnit/Intersection/IntersectionTests.cs
  src/GShark/Core/Transform.cs
  src/GShark/Core/TransformMatrix.cs
  src/GShark/Core/Trigonometry.cs
  src/GShark/Enumerations/EvaluateSurfaceDirection.cs
  src/GShark/Enumerations/RotationAxis.cs
  src/GShark/Enumerations/SplitDirection.cs
  src/GShark/Enumerations/SurfaceDirection.cs
  src/GShark/Evaluate/Curve.cs
  src/GShark/GShark.csproj
  src/GShark/Geometry/Arc.cs
  src/GShark/Geometry/BoundingBox.cs
  src/GShark/Geometry/Circle.cs
  src/GShark/Geometry/Line.cs
  src/GShark/Geometry/NurbsBase.cs
  src/GShark/Geometry/NurbsCurve.cs
  src/GShark/Geometry/NurbsSurface.cs
  src/GShark/Geometry/Plane.cs
  src/GShark/Geometry/Point3.cs
  src/GShark/Geometry/Point4.cs
  src/GShark/Geometry/Polygon.cs
  src/GShark/Geometry/Polyline.cs
  src/GShark/Interfaces/IGeometry.cs
  src/GShark/Interfaces/ITransformable.cs
Labels: major

#394 Update release draft
  .github/workflows/release-drafter.yml
Labels: major

#395 Updated the index.md
  docs/index.md
Labels: documentation :book:, patch
